// Regression on real filings. Every real-deals fixture, mapped onto line
// items, must build the same inputs as the harness's derive() did. The
// expected values are derive()'s frozen output (scripts/real-deals/expected,
// regenerated by `npm run real-deals:snapshot`), not numbers written here.
//
// Each mapping copies cited fixture figures onto app line items. Where the
// fixture cites a figure in a different shape than the app asks for, the
// mapping says so in a comment. Those are the differences to explain.

import { buildBorrowerInputs } from './borrowerBuild';
import type { BorrowerFinancials, LineItemKey } from './borrowerBuild';

/* eslint-disable @typescript-eslint/no-var-requires */
const fixture = (c: string) => require(`../../scripts/real-deals/fixtures/${c}.json`);
const expected = (c: string) => require(`../../scripts/real-deals/expected/${c}.json`);

function fig(fx: any, k: string): number {
  const f = fx.figures[k];
  const v = f?.manual ? f.manual.value : f?.value;
  if (v === null || v === undefined) throw new Error(`${fx.borrower?.name}: figure ${k} has no value`);
  return v;
}

// Cash taxes, rent and working capital, the same for every case. The fixture
// cites the working capital increase as a positive build. The app line keeps
// the cash-flow statement's sign, so it goes in negated.
function cashFlowLines(fx: any): Partial<Record<LineItemKey, number>> {
  return {
    incomeTaxesPaid: fig(fx, 'cashTaxes'),
    rentExpense: fig(fx, 'leasePayments'),
    workingCapitalChange: -fig(fx, 'workingCapitalIncrease'),
  };
}

function financials(fx: any, values: Partial<Record<LineItemKey, number>>, judgments: Record<string, unknown> = {}): BorrowerFinancials {
  const all = { ...cashFlowLines(fx), ...values };
  const lineItems = Object.fromEntries(Object.entries(all).map(([k, v]) => [k, { value: v, origin: 'typed' }]));
  const f: BorrowerFinancials = { fiscalYearEnd: fx.fiscalYearEnd || 'fixture', lineItems, ebitdaSource: 'built' };
  // Confirm every proposal, then apply the case's own calls on top.
  const proposed = buildBorrowerInputs(f).judgments;
  f.judgments = Object.fromEntries(proposed.map((j) => [j.id, { confirmed: j.value }]));
  Object.entries(judgments).forEach(([id, v]) => { f.judgments![id] = { confirmed: v }; });
  return f;
}

// The fixtures cite total debt as one figure (components summed by the
// harness, or a manual total). It goes in as term loans and notes with a
// zero revolver. Finance leases sit inside that total for DXP, H&E and Titan.
//
// The app's depreciation proxy is D&A less amortization of intangibles.
// DXP and H&E cite depreciation instead, so amortization is mapped as
// D&A - depreciation, both cited figures.
const CASES: Record<string, (fx: any) => BorrowerFinancials> = {
  'dxp-fy2025': (fx) => financials(fx, {
    revenue: fig(fx, 'revenue'),
    operatingIncome: fig(fx, 'operatingIncome'),
    depreciationAmortization: fig(fx, 'depreciationAmortization'),
    amortizationOfIntangibles: fig(fx, 'depreciationAmortization') - fig(fx, 'depreciation'),
    interestPaid: fig(fx, 'interestPaid'),
    currentMaturities: fig(fx, 'currentMaturities'),
    revolver: 0,
    termLoansAndNotes: fig(fx, 'totalDebt'),
  }),

  'hee-fy2024': (fx) => financials(fx, {
    revenue: fig(fx, 'revenue'),
    operatingIncome: fig(fx, 'operatingIncome'),
    depreciationAmortization: fig(fx, 'depreciationAmortization'),
    amortizationOfIntangibles: fig(fx, 'depreciationAmortization') - fig(fx, 'depreciation'),
    interestPaid: fig(fx, 'interestPaid'),
    // Finance lease principal only (622K). The ABL and notes have nothing due in 12 months.
    currentMaturities: fig(fx, 'currentMaturities'),
    revolver: 0,
    termLoansAndNotes: fig(fx, 'totalDebt'),
  }),

  // Hertz: the fixture cites non-vehicle interest, D&A and debt only, so the
  // vehicle items are already out and the fleet row never triggers. This
  // case checks the pretax start, not the fleet treatment.
  'hertz-fy2025': (fx) => financials(fx, {
    revenue: fig(fx, 'revenue'),
    pretaxIncome: fig(fx, 'pretaxIncome'),
    interestExpense: fig(fx, 'nonVehicleInterest'),
    depreciationAmortization: fig(fx, 'nonVehicleDA'),
    amortizationOfIntangibles: fig(fx, 'nonVehicleDA') - fig(fx, 'nonVehicleDepreciation'),
    interestPaid: fig(fx, 'interestPaid'),
    currentMaturities: fig(fx, 'currentMaturities'),
    revolver: 0,
    termLoansAndNotes: fig(fx, 'totalDebt'),
  }),

  // Titan: cash interest is reported only in total, so the fixture uses
  // non-floorplan interest EXPENSE. It goes in as interest paid with
  // floorplan marked as not inside it. Same number as derive(), same caveat.
  'titan-fy2026': (fx) => financials(fx, {
    revenue: fig(fx, 'revenue'),
    operatingIncome: fig(fx, 'operatingIncome'),
    depreciationAmortization: fig(fx, 'depreciationAmortization'),
    amortizationOfIntangibles: fig(fx, 'amortizationOfIntangibles'),
    floorplanInterest: fig(fx, 'floorplanInterest'),
    floorplanPayable: fig(fx, 'floorplanPayable'),
    interestPaid: fig(fx, 'otherInterest'),
    currentMaturities: fig(fx, 'currentMaturities'),
    revolver: 0,
    termLoansAndNotes: fig(fx, 'totalDebt'),
  }, { floorplanInterestInInterestPaid: false }),
};

const FIELDS = [
  'annualRevenue', 'ebitda', 'totalExistingDebt', 'actualAnnualDebtService', 'maintenanceCapex',
  'cashTaxes', 'leasePayments', 'workingCapitalIncrease',
] as const;

describe.each(Object.keys(CASES))('%s builds the same inputs as derive()', (c) => {
  const fx = fixture(c);
  const want = expected(c).inputs;
  const r = buildBorrowerInputs(CASES[c](fx));

  test('no errors', () => {
    expect(r.errors).toEqual([]);
  });

  test.each(FIELDS)('%s', (field) => {
    expect(r.inputs[field]).toBeCloseTo(want[field], 0);
  });
});

test('Titan uses floorplan out: interest deducted, payable excluded', () => {
  const r = buildBorrowerInputs(CASES['titan-fy2026'](fixture('titan-fy2026')));
  expect(r.treatment.floorplan).toBe('out');
  expect(r.derivations.ebitda.formula).toBe('Operating income + Depreciation and amortization - Floorplan interest');
  expect(r.derivations.totalExistingDebt.notes).toContain('Floorplan payable excluded, floorplan out.');
});

test('a working-capital release and a tax refund count as 0 in both the build and derive()', () => {
  const r = buildBorrowerInputs(CASES['titan-fy2026'](fixture('titan-fy2026')));
  expect(r.inputs.workingCapitalIncrease).toBe(0);
  expect(r.inputs.cashTaxes).toBe(0);
  expect(expected('titan-fy2026').inputs.workingCapitalIncrease).toBe(0);
});

test('Hertz has negative EBITDA and it passes through', () => {
  const r = buildBorrowerInputs(CASES['hertz-fy2025'](fixture('hertz-fy2025')));
  expect(r.inputs.ebitda).toBeLessThan(0);
  expect(r.judgments.find((j) => j.id === 'ebitdaStart')?.value).toBe('pretaxIncome');
});
