#!/usr/bin/env node
// ============================================================
// Freeze derive() output per fixture into expected/<case>.json.
//
//   npm run real-deals:snapshot
//
// Regression baseline for the in-app financials builder (Workstream A):
// for the same sourced figures, the app must produce the same Tranche
// inputs. Re-run only when a fixture changes on purpose, and commit the
// diff with the reason.
// ============================================================

const fs = require('fs');
const path = require('path');
const { derive } = require('./lib/derive');

const ROOT = __dirname;
const outDir = path.join(ROOT, 'expected');
fs.mkdirSync(outDir, { recursive: true });

for (const file of fs.readdirSync(path.join(ROOT, 'fixtures')).filter((f) => f.endsWith('.json')).sort()) {
  const fx = JSON.parse(fs.readFileSync(path.join(ROOT, 'fixtures', file), 'utf8'));
  const { inputs, derivations, blockers, caveats } = derive(fx);
  const snapshot = {
    case: fx.case,
    note: 'Generated by snapshot.js from the fixture. Do not edit by hand.',
    builds: fx.builds || null,
    inputs,
    derivations,
    caveats,
    blockers,
  };
  fs.writeFileSync(path.join(outDir, file), JSON.stringify(snapshot, null, 2) + '\n');
  console.log(`${file}: ${derivations.length} derivations, ${blockers.length} blockers`);
}
